name: Code review
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: fxchen/code-review@latest
        with:
          model: 'gpt-4o-mini'
          openai-key: ${{ secrets.OPENAI_API_KEY }}
